version: '2'
services:
  mysql:
    build: ./images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
  phpmyadmin:
    build: ./images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "6060:80"
    links:
      - mysql:db
  wildfly:
      build: ./images/wildfly
      links:
       - mysql:db
      ports:
        - "9090:8080"
        - "9990:9990"